GuestBook/Controllers/Api/GuestsController.cs
using GuestBook.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper;
using GuestBook.Models;
using System.Data.Entity;

namespace GuestBook.Controllers.Api
{
    public class GuestsController : ApiController
    {
        private ApplicationDbContext _context;

        public GuestsController()
        {
            _context = new ApplicationDbContext();
        }


        // GET /api/guests/{query}
        /// <summary>
        /// Get Guests by name or name's substring.
        /// </summary>
        /// <param name="query">Name or its part of Guest</param>
        /// <returns>Guest's Data Transfer Object of every found Guest</returns>
        public IHttpActionResult GetGuests(string query = null)
        {
            var guestsQuery = _context.Guests.Include(g => g.GuestType).Include(g => g.PaymentType);

            if (!String.IsNullOrWhiteSpace(query))
                guestsQuery = guestsQuery.Where(c => c.Name.Contains(query));

            var guestsDtos = guestsQuery
                .ToList()
                .Select(Mapper.Map<Guest, NewGuestDto>);

            return Ok(guestsDtos);
        }


        //GET /api/guests/1
        /// <summary>
        /// Get Guest by id
        /// </summary>
        /// <param name="id">Id of Guest</param>
        /// <returns>Found Guest's DTO</returns>
        public IHttpActionResult GetGuest(int id)
        {
            var guest = _context.Guests.SingleOrDefault(g => g.Id == id);

            if (guest == null)
                return NotFound();
            return Ok(Mapper.Map<Guest, NewGuestDto>(guest));
        }

        /// <summary>
        /// Create Guest according to posted DTO. 
        /// </summary>
        /// <param name="newGuest">Posted Guest's DTO form</param>
        /// <returns>Created Guest details</returns>
        [HttpPost]
        public IHttpActionResult CreateGuest(NewGuestDto newGuest)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var guest = Mapper.Map<NewGuestDto, Guest>(newGuest);
            
            guest.GuestType = _context.GuestTypes.Single(gt => gt.Id == newGuest.GuestTypeId);
            guest.PaymentType = _context.PaymenTypes.Single(gt => gt.Id == newGuest.PaymentTypeId);

            _context.Guests.Add(guest);
            _context.SaveChanges();

            newGuest.Id = guest.Id;
            return Created(new Uri(Request.RequestUri + "/" + guest.Id), newGuest);
        }
    }
}

GuestBook/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GuestBook.Models;
using GuestBook.ViewModels;

namespace GuestBook.Controllers
{
    public class EventController : Controller
    {
        private ApplicationDbContext _context;

        public EventController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        /// <summary>
        /// Controller redirecting to form of new event.
        /// </summary>
        /// <returns>View with empty form.</returns>
        public ActionResult New()
        {
            var viewModel = new EventFormViewModel
            {
                Guests = new List<Guest>(),
            };
            return View(viewModel);
        }

        /// <summary>
        /// Determine whether to get View with past event or present ones.
        /// </summary>
        /// <param name="isPassed">Determine if event was in the past</param>
        /// <returns>View wtih events</returns>
        public ActionResult Index(bool isPassed = false)
        {
            var events = _context.Events.ToList();
            var today = DateTime.Today;
            events = isPassed ? events.Where(e => e.DateEnd < today).ToList() : events.Where(e => e.DateEnd > today).ToList();
            return View(events);
        }

        /// <summary>
        /// Controller redirecting to form for editing event by id.
        /// </summary>
        /// <param name="id">ID of Event</param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            var eventInDb = _context.Events.Single(e => e.Id == id);

            var viewModel = new EventFormViewModel
            {
                Name = eventInDb.Name,
                Address = eventInDb.Address,
                DateBeg = eventInDb.DateBeg,
                DateEnd = eventInDb.DateEnd,
                Information = eventInDb.Information,
                Guests = _context.GuestOfEvents.Where(ge => ge.Event.Id == id).Select(ge => ge.Guest).ToList(),
                IsNewForm = false,
                Id = eventInDb.Id
            };
            return View("Edit", viewModel);
        }
    }
}

GuestBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")

    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - GuestBook</p>
        </footer>
    </div>

@Scripts.Render("~/bundles/lib")

@RenderSection("scripts", required: false)
</body>
</html>

GuestBook/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("GuestBook", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @*<li>@Html.ActionLink("(API)Add Business Client", "CreateBusinessClientApi", "Guests")</li>*@
                <li>@Html.ActionLink("Upcoming events", "Index", "Event")</li>
                <li>@Html.ActionLink("Passed events", "Index", "Event", new { isPassed = true }, null)</li>
                <li>@Html.ActionLink("Add Event", "New", "Event")</li>
                <li>@Html.ActionLink("Create Business Client", "CreateClient", "Guests", new {clientType = "business"}, null)</li>
                <li>@Html.ActionLink("Create Private Client", "CreateClient", "Guests", new {clientType = "private"}, null)</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>